version: 4.2
runners:
  high:
    config-id: 3
pipeline-when:
  equal:
    - << event.ref >>
    - refs/heads/main
images:
  maven:
    image: maven:3.8.5-openjdk-17
    auth:
      username: vipinkumarh
      password: << env.DOCKER_PASS >>
jobs:
  unit-test:
    steps:
      - mvn surefire-report:report
      - ls
      - cd target
      - ls
      - cd site
      - ls
    artifacts:
      upload:
        - type: zip
          regex:
            -  /target/site/**
          name: junit.zip
          location: stratus://<< env.BUCKET_NAME >>/
  package:
    steps:
      - mvn clean package -DskipTests=true
    artifacts:
      upload:
        - type: file
          name: SNAPSHOT.jar
          file: target/demo-0.0.1-SNAPSHOT.jar
          location: stratus://<< env.BUCKET_NAME >>/
  catalyst-deploy:
    when:
      equal:
        - << status.build.package >>
        - success
    steps:
      - printenv
      - npm install -g zcatalyst-cli@beta
      - >-
        catalyst deploy appsail --name spring-boot --build-path
        "/catalyst/SNAPSHOT.jar" --stack java17 --platform javase --command "sh
        -c 'java -jar SNAPSHOT.jar
        --server.port=\${X_ZOHO_CATALYST_LISTEN_PORT}'" --verbose
    artifacts:
      download:
        - type: file
          name: SNAPSHOT.jar
          file: /SNAPSHOT.jar
          location: stratus://<< env.BUCKET_NAME >>/
stages:
  - name: test
    image: maven
    jobs:
      - unit-test
  - name: build
    image: maven
    jobs:
      - package
  - name: deploy
    jobs:
      - catalyst-deploy