version: 4.2
runners:
  high:
    config-id: 3
pipeline-when:
  equal:
    - << event.ref >>
    - refs/heads/main
images:
  maven:
    image: maven:3.8.5-openjdk-17
    auth:
      username: hvipinkumar
      password: << env.DOCKER_PASS >>
  docker:
    image: docker:latest
    auth:
      username: hvipinkumar
      password: << env.DOCKER_PASS >>
jobs:
  unit-test:
    steps:
      - printenv
      - mvn surefire-report:report
    artifacts:
      upload:
        - type: zip
          regex:
            - /catalyst/target/site/**
          name: junit.zip
          location: stratus://pipeline-test-2/
  package:
    steps:
      - mvn clean package -DskipTests=true
    artifacts:
      upload:
        - type: file
          name: SNAPSHOT.jar
          file: /catalyst/target/demo-0.0.1-SNAPSHOT.jar
          location: stratus://pipeline-test-2/
  docker-build:
    runner: high
    image: docker
    steps:
      - apk update && apk upgrade
      - apk add curl
      - >-
        (curl -sSL
        "https://github.com/buildpacks/pack/releases/download/v0.33.2/pack-v0.33.2-linux.tgz"
        | tar -C /usr/local/bin/ --no-same-owner -xzv pack)
      - >-
        pack build sample-spring-boot --builder
        paketobuildpacks/builder-jammy-tiny --env BP_JVM_VERSION=21
      - docker save -o spring-img.tar sample-spring-boot
      - du -sh spring-img.tar
    artifacts:
      upload:
        - type: file
          name: spring-img.tar
          file: /catalyst/spring-img.tar
          location: stratus://pipeline-test-2/
  docker-deploy:
    runner: high
    when:
      equal:
        - << status.build.docker-build >>
        - success
    image: docker
    steps:
      - docker load -i spring-img.tar
      - docker images
      - docker tag sample-spring-boot hvipinkumar/private:spring-boot
      - docker images
      - docker login -u hvipinkumar -p << env.DOCKER_PASS >> docker.io
      - docker push hvipinkumar/private:spring-boot
    artifacts:
      download:
        - type: file
          name: spring-img.tar
          file: /spring-img.tar
          location: stratus://pipeline-test-2/
  catalyst-deploy:
    when:
      equal:
        - << status.build.package >>
        - success
    steps:
      - ls
      - >-
        catalyst deploy appsail --name spring-boot --build-path
        "/catalyst/SNAPSHOT.jar" --stack java17 --platform javase --command "sh
        -c 'java -jar SNAPSHOT.jar
        --server.port=\${X_ZOHO_CATALYST_LISTEN_PORT}'" --verbose
    artifacts:
      download:
        - type: file
          name: SNAPSHOT.jar
          file: /SNAPSHOT.jar
          location: stratus://pipeline-test-2/
  approval-job:
    type: approval
    specification:
      reviewers:
        - vipin.kumar+lz_cicd_26@zohotest.com
      message: >-
        Hi,

        Kindly find the Test Report below. Verify the results & Kindly approve
        the pipeline.

        <a
        href="https://pipeline-test-2-development.lzstratus.com/junit.zip">Results</a>
stages:
  - name: build
    image: maven
    jobs:
      - unit-test
      - approval-job
      - - package
        - docker-build
  - name: deploy
    when:
      not: false
    jobs:
      - - catalyst-deploy
        - docker-deploy